version: '3.8'
services:
  web:
    build: .
    container_name: sub-converter
    ports:
      - "5000:5000"
    volumes:
      - ./app/data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    restart: always
